apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    run: hello
  name: hello
spec:
  replicas: 1
  selector:
    run: hello
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hello
    spec:
      containers:
      - args:
        - --conf
        - /etc/caddy/config/caddyfile.conf
        image: aosqe/caddy-docker
        imagePullPolicy: Always
        name: hello
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/serving-cert
          name: volume-xfqr1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: volume-xfqr1
        secret:
          secretName: ssl-key
  test: false
  triggers:
  - type: ConfigChange
status: {}

