apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-preferred-weight-101
spec:
  containers:
    - image: "docker.io/ocpqe/hello-pod"
      name: hello-pod
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 101
        preference:
          matchExpressions:
          - key: "zone"
            operator: In
            values:
            - us
