apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-preferred-weight-fraction
spec:
  containers:
    - image: "docker.io/ocpqe/hello-pod"
      name: hello-pod
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 2.5
        preference:
          matchExpressions:
          - key: "zone"
            operator: In
            values:
            - us
