apiVersion: v1
kind: Pod
metadata:
  name: invailidfoo1
spec:
  containers:
  - name: my-container1
    image: "docker.io/deshuai/hello-pod:latest"
    resources:
      requests:
        cpu: 0.1
        pod.alpha.kubernetes.io/opaque-int-resource-foo: 0.1
