apiVersion: v1
kind: Template
metadata:
  annotations:
    description: "serviceinstance-lastop-template"
  name: serviceinstance-lastop-template
objects:
  -
    apiVersion: servicecatalog.k8s.io/v1beta1
    kind: ServiceInstance
    metadata:
      name: "${INSTANCE_NAME}"
      namespace: "${INSTANCE_NAMESPACE}"
    spec:
      clusterServiceClassExternalName: "${CLASS_EXTERNAL_NAME}"
      clusterServicePlanExternalName: "${PLAN_EXTERNAL_NAME}"
parameters:
  -
    name: INSTANCE_NAME
    description: "serviceinstance name"
    generate: expression
    value: "dh-lastop-cem-demo-apb"
  -
    name: INSTANCE_NAMESPACE
    description: "serviceinstance namespace"
    generate: expression
    value: "auto-asb"
  -
    name: CLASS_EXTERNAL_NAME
    description: "clusterserviceclass external name"
    generate: expression
    value: "dh-lastop-cem-demo-apb"
  -
    name: PLAN_EXTERNAL_NAME
    description: "clusterserviceplan external plan"
    generate: expression
    value: "custom-err-msg"
