apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: ups-instance
  namespace: test-ns
spec:
  externalClusterServiceClassName: user-provided-service
  externalClusterServicePlanName: default
