apiVersion: v1
kind: Pod
metadata:
  name: pod-toleration-red
spec:
  containers:
    - image: "docker.io/ocpqe/hello-pod:latest"
      name: hello-pod
  tolerations:
  - key: color
    value: red
    operator: Equal
    effect: NoSchedule
