apiVersion: v1
kind: Pod
metadata:
  name: wildcard-toleration
spec:
  containers:
    - image: "docker.io/ocpqe/hello-pod"
      name: hello-pod
  tolerations:
  - key: dedicated
    operator: Exists
    effect: NoSchedule