apiVersion: v1
kind: Pod
metadata:
  name: pod-toleration-dedicated
spec:
  containers:
    - image: "docker.io/ocpqe/hello-pod"
      name: hello-pod
  tolerations:
  - key: dedicated
    value: special-user
    operator: Equal
    effect: NoSchedule