apiVersion: metering.openshift.io/v1alpha1
kind: Metering
metadata:
  name: "operator-metering"
spec:
  reporting-operator:
  spec:
    route:
      enabled: true
    authProxy:
      enabled: true
      htpasswdData: |
        testuser-0:{SHA}hmqIQ3qX3U8o1WL4yih+pwGOo2k=
      cookieSeed: "2bc7283ca4c0b193fc0625525039478bc2dffa53c368440f4a8a417862de87ae"
      subjectAccessReviewEnabled: true
      delegateURLsEnabled: true
