apiVersion: v1
kind: Pod
metadata:
  name: nfs
  namespace: default
spec:
  containers:
  - name: nginx-nfs
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: test
    flexVolume:
      driver: "openshift.com/nfs"
      fsType: "nfs"
      capabilities:
        selinuxRelabel: false
      options:
        server: "10.66.147.137"
        share: "nfs"
