apiVersion: v1
kind: Pod
metadata:
  name: nginx-dummy-attachable
spec:
  containers:
  - name: nginx-dummy-attachable
    image: nginx
    volumeMounts:
    - name: dummy-attachable
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: dummy-attachable
    flexVolume:
      driver: "openshift.com/dummy-attachable"
