apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: test
    flexVolume:
      driver: "openshift.com/lvm"
      fsType: "ext4"
      options:
        volumeID: "lvol0"
        size: "100m"
        volumegroup: "openshift_vg"
