apiVersion: v1
kind: Pod
metadata:
  name: mydatabase
spec:
  containers:
  - env:
    - name: MYSQL_USER
      value: userH87
    - name: MYSQL_PASSWORD
      value: bJYW5oTf
    - name: MYSQL_DATABASE
      value: root
    image: openshift/mysql-55-centos7:latest
    name: ruby-helloworld-database
    ports:
    - containerPort: 3306
      protocol: TCP
