apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  labels:
    app: example-pod
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
spec:
  containers:
  - name: example-pod
    image: app:v1
    ports:
    - containerPort: 80
