---
apiVersion: v1
kind: Pod
metadata:
  name: base-ansible-pod
  labels:
    name: base-ansible-pod
spec:
  containers:
  - env:
    - name: http_proxy
      value: "http://file.rdu.redhat.com:3128"
    - name: https_proxy
      value: "http://file.rdu.redhat.com:3128"
    name: base-ansible-pod
    image: aosqe/fedora_base
    securityContext:
      privileged: true

