kind: SecurityContextConstraints
apiVersion: v1
fsGroup:
  type: RunAsAny
groups:
- system:serviceaccounts
- system:authenticated
metadata:
  labels:
    name: scc-runasany-<%= cb.scc_name %>
  name: scc-runasany-<%= cb.scc_name %>
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
allowHostDirVolumePlugin: false
allowHostIPC: true
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: null
