seLinuxContext:
  type: RunAsAny
runAsUser:
  type: MustRunAsNonRoot
apiVersion: v1
groups:
- system:serviceaccounts:default
kind: SecurityContextConstraints
metadata:
  labels:
    name: scc-user-mustrunasnonroot
  name: scc-user-mustrunasnonroot
