allowHostNetwork: true
allowHostPorts: true
apiVersion: v1
kind: SecurityContextConstraints
metadata:
  name: hostport
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:default:router
