allowedCapabilities:
- SETPCAP
- MKNOD
- AUDIT_WRITE
- CHOWN
- NET_RAW
- DAC_OVERRIDE
- FOWNER
- FSETID
- KILL
- SETGID
- SETUID
- NET_BIND_SERVICE
- SYS_CHROOT
- SETFCAP
- SYS_MODULE
- SYS_RAWIO
- SYS_PACCT
- SYS_ADMIN
- SYS_NICE
- SYS_RESOURCE
- SYS_TIME
- SYS_TTY_CONFIG
- AUDIT_CONTROL
- MAC_OVERRIDE
- MAC_ADMIN
- NET_ADMIN
- SYSLOG
- DAC_READ_SEARCH
- LINUX_IMMUTABLE
- NET_BROADCAST
- IPC_LOCK
- IPC_OWNER
- SYS_PTRACE
- SYS_BOOT
- LEASE
- WAKE_ALARM
- BLOCK_SUSPEND
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
apiVersion: v1
groups:
- system:serviceaccounts:default
kind: SecurityContextConstraints
metadata:
  labels:
    name: scc-with-all-cap
  name: scc-with-all-cap
