allowHostDirVolumePlugin: true
allowHostNetwork: true
allowHostPorts: true
allowPrivilegedContainer: true
allowedCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
apiVersion: v1
kind: SecurityContextConstraints
metadata:
  name: super-#NAME#
groups:
- system:serviceaccounts:#NS#
users:
- #ACCOUNT#
