allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
apiVersion: v1
groups:
- system:serviceaccounts:default
kind: SecurityContextConstraints
metadata:
  labels:
    name: scc-pri
  name: scc-pri
