allowHostNetwork: true
allowHostPorts: true
apiVersion: v1
kind: SecurityContextConstraints
metadata:
  name: hostport-#NS#
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
groups:
- system:serviceaccounts:#NS#
