allowHostDirVolumePlugin: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
apiVersion: v1
kind: SecurityContextConstraints
metadata:
  name: scc-hostdir-#NS#
groups:
- system:serviceaccounts:#NS#
