apiVersion: logging.openshift.io/v1alpha1
kind: LogForwarding
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
    - name: fluentd-created-by-user
      type: forward
      endpoint: 'fluentdserver1.openshift-logging.svc:24224'
      insecure: true
  pipelines:
    - name: app-pipeline
      inputType: logs.app
      outputRefs:
        - fluentd-created-by-user
    - name: infra-pipeline
      inputType: logs.infra
      outputRefs:
        - fluentd-created-by-user
    - name: audit-pipeline
      inputType: logs.audit
      outputRefs:
        - fluentd-created-by-user
