apiVersion: v1
kind: Pod
metadata:
  name: macvlan-passthru-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-passthru-conf
spec:
  containers:
  - name: macvlan-passthru-pod
    image: docker.io/bmeng/centos-network
