apiVersion: v1
kind: Pod
metadata:
  name: host-device-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: host-device-conf
spec:
  containers:
  - name: host-device-pod
    image: docker.io/bmeng/centos-network
