apiVersion: v1
kind: Pod
metadata:
  name: two-host-device-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: host-device1-conf, host-device2-conf
spec:
  containers:
  - name: two-host-device-pod
    image: docker.io/bmeng/centos-network
