apiVersion: v1
kind: Pod
metadata:
  generateName: two-host-device-pod-
  annotations:
    k8s.v1.cni.cncf.io/networks: host-device1, host-device2
spec:
  containers:
  - name: two-host-device-pod
    image: docker.io/bmeng/centos-network
