apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-invalid-topologykey-empty
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: security
            operator: In
            values:
            - s1
  containers:
  - name: pod-affinity
    image: docker.io/ocpqe/hello-pod
