apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-doesnotexist-value
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: security
            operator: DoesNotExist
            values:
            - s1
        topologyKey: kubernetes.io/hostname
  containers:
  - name: pod-affinity
    image: docker.io/ocpqe/hello-pod
