apiVersion: v1
kind: Pod
metadata:
  name: cinder
  labels: 
    name: cinder
spec: 
  containers: 
    - resources:
        limits :
          cpu: 0.5
      image: aosqe/hello-openshift
      name: cinder
      ports: 
        - containerPort: 3306
          name: mysql
      volumeMounts:
          # name must match the volume name below
        - name: cinder-volume
          mountPath: /mnt
  volumes:
    - name: cinder-volume
      cinder:
        volumeID: 614ac6ef-423d-490b-be4a-16fa829f20cc
        fsType: ext4
