apiVersion: v1
kind: Service
metadata:
  labels:
    test: "1234"
  name: mysvc
  namespace: myproject
spec:
  clusterIP:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    router: router
  sessionAffinity: None
  type: ExternalName
  externalName: www.myproject.com
