kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: incorrect-policy-1
spec:
  podSelecter:
  ingress:
  - ports:
    - protocol: TCP
      port: 8080
    - from:
      - podSelector: {}
