apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-logging-operator
  namespace: openshift-logging
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: cluster-logging-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      - command:
        - cluster-logging-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations['olm.targetNamespaces']
        - name: OPERATOR_NAME
          value: cluster-logging-operator
        - name: ELASTICSEARCH_IMAGE
          value: registry.stage.redhat.io/openshift4/ose-logging-elasticsearch5:v4.1.4-201906271212
        - name: FLUENTD_IMAGE
          value: registry.stage.redhat.io/openshift4/ose-logging-fluentd:v4.1.4-201906271212
        - name: KIBANA_IMAGE
          value: registry.stage.redhat.io/openshift4/ose-logging-kibana5:v4.1.4-201906271212
        - name: CURATOR_IMAGE
          value: registry.stage.redhat.io/openshift4/ose-logging-curator5:v4.1.4-201906271212
        - name: OAUTH_PROXY_IMAGE
          value: registry.stage.redhat.io/openshift4/ose-oauth-proxy:v4.1.4-201906271212
        - name: RSYSLOG_IMAGE
          value: quay.io/openshift/origin-logging-rsyslog:latest
        image: registry.stage.redhat.io/openshift4/ose-cluster-logging-operator:v4.1.4-201906271212
        imagePullPolicy: IfNotPresent
        name: cluster-logging-operator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cluster-logging-operator
      serviceAccountName: cluster-logging-operator
      terminationGracePeriodSeconds: 30
