apiVersion: v1
kind: Pod
metadata:
  name: pod-burstable
spec:
  containers:
  - name: burstable
    image: openshift/mysql-55-centos7:latest
    env:
    - name: MYSQL_USER
      value: userSUM
      name: MYSQL_PASSWORD
      value: P5J6s8wf
      name: MYSQL_DATABASE
      value: root
      name: MYSQL_ROOT_PASSWORD
      value: W5J6s8wf
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
