apiVersion: v1
kind: DeploymentConfig
metadata:
  name: custom-deployment
spec:
  replicas: 2
  selector:
    name: custom-deployment
  strategy:
    customParams:
      command:
      - /bin/sh
      - -c
      - |
        set -e
        openshift-deploy --until=50%
        echo Halfway
        openshift-deploy
        echo Finished
    recreateParams:
      pre:
        execNewPod:
          command:
          - /bin/echo
          - test pre hook executed
          containerName: myapp
        failurePolicy: Abort
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: custom-deployment
    spec:
      containers:
      - command:
        - /bin/sleep
        - "100"
        image: docker.io/centos:centos7
        imagePullPolicy: IfNotPresent
        name: myapp
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 0
  test: false
  triggers:
  - type: ConfigChange

