apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generateName: "elasticsearch-"
  namespace: "openshift-operators-redhat"
spec:
  channel: preview
  installPlanApproval: Automatic
  source: "elasticsearch"
  sourceNamespace: "openshift-marketplace"
  name: "elasticsearch-operator"
