apiVersion: v1
data:
  fluent.conf: |
    <source>
      @type forward
      <security>
        self_hostname $HOSTNAME
        shared_key oo_share_key
      </security>
    </source>
kind: ConfigMap
metadata:
  name: fluentdserver2
  namespace: openshift-logging
