apiVersion: v1
data:
  secure-forward.conf: |
    <store>
      @type forward
      <server>
        host 192.168.1.2
        port 24224
      </server>
      <security>
        self_hostname HOSTNAME
        shared_key secret
      </security>
    </store>
