apiVersion: v1
kind: Pod
metadata:
  generateName: priorityh
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: docker.io/aosqe/sigcapture:latest
    imagePullPolicy: IfNotPresent
    resources:
     requests:
      cpu: 500m
      memory: 500Mi
  priorityClassName: priorityh
  terminationGracePeriodSeconds: 120

