apiVersion: v1
kind: Pod
metadata:
  name: secret-keys-permission-pod
spec:
  containers:
  - name: secret-keys-permission-pod
    image: redis
    volumeMounts:
    - name: foo-volume
      mountPath: "/etc/foo"
  volumes:
  - name: foo-volume
    secret:
      secretName: test-secret
      items:
      - key: data-1
        path: mysecret/share
        mode: 0777
      - key: data-2
        path: mysecret/private
        mode: 0500
