apiVersion: v1
kind: Pod
metadata:
  name: secret-permission-pod
spec:
  containers:
  - name: secret-permission-pod
    image: redis
    volumeMounts:
    - name: foo-volume
      mountPath: "/etc/foo"
  volumes:
  - name: foo-volume
    secret:
      secretName: test-secret
      defaultMode: 0744
