kind: Pod
apiVersion: v1
metadata:
  name: dapisec 
  annotations:
    build: one
    builder: qe-one
spec:
  containers:
    - name: dapicont 
      image: jhou/hello-openshift
      volumeMounts:
      - mountPath: "/mnt/dapi"
        name: dapi-volume
  securityContext:
    fsGroup: 123456
    seLinuxOptions:
      level: "s0:c8,c2"
  volumes:
    - name: dapi-volume 
      downwardAPI:
        items:
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
          - path: "name"
            fieldRef:
              fieldPath: metadata.name

