apiVersion: v1
kind: Pod
metadata:
  name: init-readiness
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  initContainers:
  - name: init
    image: centos:centos7
    command:
    - /bin/true
    readinessProbe:
      tcpSocket:
        port: 8080
  volumes:
  - name: workdir
    emptyDir: {}
