apiVersion: v1
kind: Pod
metadata:
  name: init-never-succ
spec:
  containers:
  - name: hello-pod
    image: docker.io/ocpqe/hello-pod
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  initContainers:
  - name: init
    image: centos:centos7
    command:
    - /bin/bash
    - "-c"
    - "sleep 10"
  restartPolicy: Never
  volumes:
  - name: workdir
    emptyDir: {}
