apiVersion: v1
kind: Pod
metadata:
  name: init-quota1
spec:
  containers:
  - name: hello-pod2
    image: docker.io/ocpqe/hello-pod
    ports:
    - containerPort: 80
    resources: 
      limits: 
        cpu: "150m"
        memory: "120Mi"
      requests: 
        cpu: "100m"
        memory: "100Mi"
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  - image: "docker.io/deshuai/hello-pod:latest"
    imagePullPolicy: IfNotPresent
    name: hello-pod
    ports:
      - containerPort: 8080
        protocol: TCP
    resources: 
      limits: 
        cpu: "150m"
        memory: "120Mi"
      requests: 
        cpu: "100m"
        memory: "100Mi"
  initContainers:
  - name: init1
    image: centos:centos7
    command:
    - /bin/true
    resources:  
      limits:  
        cpu: "500m"
        memory: "400Mi"
      requests:  
        cpu: "400m"
        memory: "300Mi"
  - name: init2
    image: centos:centos7
    command:
    - /bin/true
    resources:
      limits:
        cpu: "300m"
        memory: "200Mi"
      requests:
        cpu: "200m"
        memory: "100Mi"
  volumes:
  - name: workdir
    emptyDir: {}
