apiVersion: v1
kind: Pod
metadata:
  name: init-deadline
spec:
  containers:
  - name: hello-pod
    image: docker.io/ocpqe/hello-pod
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  initContainers:
  - name: init
    image: centos:centos7
    command:
    - /bin/sh
    - "-c"
    - "sleep 10"
  activeDeadlineSeconds: 15
  volumes:
  - name: workdir
    emptyDir: {}
