apiVersion: v1
kind: Pod
metadata:
  name: init-quota1
spec:
  containers:
  - name: container1
    image: kubernetes/pause
    resources: 
      limits: 
        cpu: "150m"
        memory: "120Mi"
      requests: 
        cpu: "100m"
        memory: "100Mi"
  - name: container2
    image: kubernetes/pause
    resources: 
      limits: 
        cpu: "150m"
        memory: "120Mi"
      requests: 
        cpu: "100m"
        memory: "100Mi"
  initContainers:
  - name: init1
    image: centos:centos7
    command:
    - /bin/true
    resources:  
      limits:  
        cpu: "500m"
        memory: "400Mi"
      requests:  
        cpu: "400m"
        memory: "300Mi"
  - name: init2
    image: centos:centos7
    command:
    - /bin/true
    resources:
      limits:
        cpu: "300m"
        memory: "200Mi"
      requests:
        cpu: "200m"
        memory: "100Mi"
