apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: projectname
  selfLink: /api/v1/namespaces/projectname/persistentvolumeclaims/mypvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status:
  phase: Pending
