apiVersion: v1
kind: Pod
metadata:
  name: pod-toleration-fail-operator
spec:
  containers:
  - image: "docker.io/ocpqe/hello-pod"
    name: hello-pod
  tolerations:
  - key: vip
    operator: Bigger
    effect: NoSchedule
