apiVersion: v1
kind: Pod
metadata:
  name: toleration-fail-effect
spec:
  containers:
  - image: "docker.io/ocpqe/hello-pod"
    name: hello-pod
  tolerations:
  - key: dedicated
    operator: Exists
    effect: Run
