apiVersion: v1
kind: Pod
metadata:
  name: pod-toleration-fail-no-key
spec:
  containers:
  - image: docker.io/ocpqe/hello-pod
    name: hello-pod
  tolerations:
  - operator: Equal
    effect: NoSchedule
