apiVersion: v1
kind: Pod
metadata:
  name: pod-toleration-fail
spec:
  containers:
  - image: docker.io/ocpqe/hello-pod
    name: hello-pod
  tolerations:
  - key: vip
    value: value123
    operator: Exists
    effect: NoSchedule
