apiVersion: v1
kind: PersistentVolume
metadata:
  name: vsphere
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  vsphereVolume:
    volumePath: "datastore1 volumes/myDisk"
    fsType: ext4
