apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-openshift
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
      containers:
      - name: hello-openshift
        image: yapei/hello-openshift
        ports:
        - containerPort: 80
      - name: hello-openshift-fedora
        image: yapei/hello-openshift-fedora
        ports:
        - containerPort: 8080
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
    type: RollingUpdate
