kind: PersistentVolume
apiVersion: v1
metadata:
  name: azpv-delete
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  azureDisk:
    diskName: test1.vhd
    diskURI: https://openshiftqestorage.blob.core.windows.net/vhds/test1.vhd
  persistentVolumeReclaimPolicy: Delete
