kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: azpvcnosc
  annotations:        
    volume.beta.kubernetes.io/storage-class: "" 
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
