kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: azpvcrwest
  annotations:        
    volume.beta.kubernetes.io/storage-class: wwlrs 
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
