allowedCapabilities:
- FSETID
- KILL
- INVALID_VALUE
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
apiVersion: v1
groups:
- system:serviceaccounts:default
kind: SecurityContextConstraints
metadata:
  labels:
    name: invalid-scc-cap
  name: invalid-scc-cap
