kind: PersistentVolume
apiVersion: v1
metadata:
  name: local
  annotations:
    volume.beta.kubernetes.io/mount-options: "backupvolfile-server=volfile_server2,fetch-attempts=2,log-level=WARNING,log-file=/var/log/gluster.log"
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/data01"
