kind: Pod
apiVersion: v1
metadata:
  name: localpd
  labels:
    name: frontendhttp
spec:
  containers:
    - name: myfrontend
      image: aosqe/hello-openshift
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
      - mountPath: "/mnt"
        name: local
  volumes:
    - name: local
      persistentVolumeClaim:
       claimName: localc
