apiVersion: v1
kind: Pod
metadata:
  name: pod-pull-by-digests
  labels:
    app: pod-pull-by-digests
spec:
  containers:
  - name: hello-pod
    image: docker.io/ocpqe/hello-pod@sha256:90b815d55c95fffafd7b68a997787d0b939cdae1bca785c6f52b5d3ffa70714f
    ports:
    - containerPort: 80
