apiVersion: v1
kind: Pod
metadata:
  name: hello-openshift
spec:
  containers:
  - image: openshift/hello-openshift
    name: hello-openshift
    ports:
    - containerPort: 8080
      protocol: TCP
    livenessProbe:
      failureThreshold: 3
      httpGet:
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
