kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfsdynpvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfsdyn-sc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
