apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: cinderprovisioner
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/cinder
parameters:
  availability: nova
