kind: Pod
apiVersion: v1
metadata:
  name: configsec 
spec:
  containers:
    - name: configcont 
      image: jhou/hello-openshift
      volumeMounts:
      - mountPath: "/mnt/configmap"
        name: config-volume 
  securityContext:
    fsGroup: 123456
    seLinuxOptions:
      level: "s0:c8,c2"
  volumes:
    - name: config-volume
      configMap:
        name: special-config
